### ISSUE TITLE
Add Parity Check information

### ISSUE THREAD

**Issue by adyannu** [domalab/ha-unraid#14]
**Is your feature request related to a problem? Please describe.**
 The integration could provide information about Parity Check status

**Describe the solution you'd like**
Add sensors with information about Parity as shown on Unraid UI, like: Last check, Next check, Avg. Speed, Current status, Errors count, etc.

**Additional context**
This is the information provided by Unraid UI:
![image](https://github.com/user-attachments/assets/9e6873bb-e17c-477a-974e-f97fec01d273)

**Comment by domalab** [comment]
@adyannu I had a quick look and came up with this. It will be a binary sensor. I tested on my system that does not have parity check enabled so it shows nothing but if you have it enabled then it will show you info.

![Screenshot 2024-11-14 at 5 02 40 pm](https://github.com/user-attachments/assets/13e0889e-1bd3-4ddc-82c4-3fe7f4189200)

**Comment by adyannu** [comment]
Sounds good. A binary sensor as "Unraid Parity is Valid" with the current state, and other info as Last check, Next check, Avg. Speed, Errors count could be attributes of that sensor.

**Comment by domalab** [comment]
@adyannu I released a new version with parity check sensor. Let me know if it works for you.

**Comment by mvanlijden** [comment]
Also replied in a less related topic. But Parity is shown, but not completely right.
Status is correct in de attributes, but not shown in the entity status
![image](https://github.com/user-attachments/assets/2e98ec9d-21ac-48c5-861d-8dee777d923d)

**Comment by adyannu** [comment]
Hello @domalab, thank you for your fast development... nice job!!

Here I have some feedback:

- Status: shows "Checking", but Unraid is not checking parity.
- Avg. Speed: Shows wrong unit or value (152 MB/s vs 148578 MB/s).
- Would be nice to have: "Next check scheduled" value.

**Screenshots:**

![image](https://github.com/user-attachments/assets/0a6cbdca-95db-42f6-bc59-d7d53f635fdc)

![image](https://github.com/user-attachments/assets/f6485a2b-4cd1-4f54-a7b9-f2878b079303)

**Comment by domalab** [comment]
@adyannu I made some adjustments to the parity sensor code. Not sure if it will work or not as I don't use parity. 

Copy the code files from unraid folder in repo to your custom_components\unraid folder and restart home assistant.

Best to test it on HA Dev instance if you have one.

Also, if you want to, please send me your parity-check.log file situated in \boot\config folder. I don't have enough parity log file data to check if sensor will work or not.

I also looked everywhere and couldn't find a config file on unraid that stores parity check schedule data.

**Comment by adyannu** [comment]
@domalab I tried the latest version and this is what I found:

- Status: shows correct status (valid!) 
- Average speed: still shows wrong drive or value (152 MB/s vs 148578 MB/s).
- Current speed: no longer shown.

I'm having some strange behavior with the disks, related to the last comments in #3. I'll post there. 
Also Docker container and VM services appears as not running.

Thank you for working on this nice plugin!

**Comment by domalab** [comment]
> @domalab I tried the latest version and this is what I found:
> 
> * Status: shows correct status (valid!)
> * Average speed: still shows wrong drive or value (152 MB/s vs 148578 MB/s).
> * Current speed: no longer shown.
> 
> I'm having some strange behavior with the disks, related to the last comments in #3. I'll post there. Also Docker container and VM services appears as not running.
> 
> Thank you for working on this nice plugin!

Remember to clear your browser cache when running the experimental code. I had same issue and after clearing the cache its working fine. Just HA that likes to cache old data

**Comment by domalab** [comment]
@adyannu
Parity Check Sensor added.

Not officially released yet as new version but you can use source code to test
